# Example docker compose, update the image name and the database properties to the ones you need
version: '3'
services: 
  notebook: 
    image: 'jupyter/scipy-notebook'
    container_name: 'notebook'
    ports: 
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - .:/home/jovyan/work